'''
Enchantments and their multipliers are immutable.
'''

MULTIPLIERS = {
    'PROT': (1,1),
    'FIPR': (2,1),
    'FEAT': (2,1),
    'BLPR': (4,2),
    'PRPR': (2,1),
    'THRN': (8,4),
    'RESP': (4,2),
    'DPTH': (4,2),
    'AQUA': (4,2),
    'SHRP': (1,1),
    'SMTE': (2,1),
    'BANE': (2,1),
    'KNCK': (2,1),
    'FASP': (4,2),
    'LOOT': (4,2),
    'EFFI': (1,1),
    'SILK': (8,4),
    'UNBR': (2,1),
    'FORT': (4,2),
    'POWR': (1,1),
    'PNCH': (4,2),
    'FLME': (4,2),
    'INFI': (8,4),
    'LUCK': (4,2),
    'LURE': (4,2),
    'FRST': (4,2),
    'MEND': (4,2),
    'BIND': (8,4),
    'VNSH': (8,4),
    'IMPL': (2,1), # JE has x2 the multipliers than bedrock, so use BE as standard.
    'RIPT': (4,2),
    'LOYL': (1,1),
    'CHAN': (8,4),
    'MLTI': (4,2),
    'PIER': (1,1),
    'QUIK': (2,1),
    'SOUL': (8,4),
    'SWFT': (8,4),
    }